### ISSUE TITLE
inaccurate version bounds in .cabal file

### ISSUE THREAD

**Issue by hvr** [alcidesv/second-transfer#6]
As can be seen on http://matrix.hackage.haskell.org/package/second-transfer several releases of `second-transfer` are suffering from bit-rotting install-plans due to omitted upper bounds or inaccurate version bounds in general.

**Comment by alcidesv** [comment]
Fixed!

**Comment by hvr** [comment]
@alcidesv I'm afraid it's not fixed yet completely:

```
Configuring second-transfer-0.10.0.4...
Preprocessing library second-transfer-0.10.0.4...

hs-src/SecondTransfer/TLS/CoreServer.hs:3:14:
    Unsupported extension: PartialTypeSignatures
```

so that file should have been listed as `other-extensions:` in the .cabal file so the cabal solver knows which features the Haskell compiler needs to provide, and even if that one was adressed:

```
[ 1 of 47] Compiling SecondTransfer.Http2.CalmState ( hs-src/SecondTransfer/Http2/CalmState.hs, /tmp/second-transfer-0.10.0.4/dist-newstyle/build/second-transfer-0.10.0.4/build/SecondTransfer/Http2/CalmState.o )

hs-src/SecondTransfer/Http2/CalmState.hs:16:28:
    Not in scope: type constructor or class ‘Word’

hs-src/SecondTransfer/Http2/CalmState.hs:16:34:
    Not in scope: type constructor or class ‘Word’
```

which means that the code doesn't work with `base-4.7` anyway. So the lower bound on `base` is still inaccurate.

I'm sure there are other inaccuracies in the `.cabal` file which will become an issue sooner or later.

Morever, somebody will have to go over all past `second-transfer` releases and add missing version bounds, as it's not enough to just release a new version of `second-transfer` with tighter version bounds. The cabal solver will happily choose an older release of `second-transfer` with less tight version bounds.

**Comment by alcidesv** [comment]
Thanks @hvr . This is mostly due to my lack of experience, I will be fixing the bounds issue. I didn't know about hackage matrix and about `other-extensions`. How can I get the "Unsupported extension" messages in my build?
